CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    CITY TEXT,
    GRADE INTEGER,
    AGE INTEGER);


INSERT INTO STUDENT (ROLL_NO, NAME, CITY, Grade, AGE) VALUES
('1','John','MUMBAI',98,18),    
('2','Ramitin','New York',100,18),    
('3','SUJIT','LONDON',87,20),    
('4','SURESH','DELHI',34,18),    
('5','AMAN','PARIS',199,20),    
('6','HARSH','MONACO',172,18);

SELECT * FROM STUDENT
WHERE CITY = 'New York' OR Grade > 100;

SELECT * FROM STUDENT
WHERE CITY = 'New York' AND Grade > 100;
